### ISSUE TITLE
Role fails on RHEL6

### ISSUE THREAD

**Issue by bbaassssiiee** [sfromm/ansible-postgresql#2] opened 2016-06-26 10:53 UTC
TASK [sfromm.postgresql : template postgresql.service] *************************
fatal: [sql]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/systemd/system does not exist"}

RHEL6 end of life is in 2020.

**Comment by sfromm** [comment] 2016-06-28 19:15
Thank you for your interest in this role.

The role only marks el7 as supported (see meta/main.yml).  That said, I'm open to patches that would support el6.  Related to #1, part of the issue is how postgresql initialization is handled differently on el6 and el7.  There are also likely parameters in postgresql.conf that may or may not be present, depending on the version of postgresql.  Is this something you want to take a crack at?

Thanks!

**Comment by bbaassssiiee** [comment] 2016-06-28 20:10
See bbaassssiiee.el_postgres_role

**Comment by sfromm** [comment] 2016-06-28 20:26
Looks like you already have something that fits your needs.  Per the README, el6 is presently not part of the goals of this role. Closing this for now, but can reopen if there's an associated pull request.  Thanks!

**Closed as completed by sfromm** 2016-06-28 20:26 UTC
